AllCops:
  DisabledByDefault: true
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.1

Lint/DuplicateMethods:
  Enabled: true

Lint/RescueException:
  Enabled: true

Lint/ShadowingOuterLocalVariable:
  Enabled: true

Lint/Syntax:
  Enabled: true

Lint/UnreachableCode:
  Enabled: true

Security/Eval:
  Enabled: true

Security/JSONLoad:
  Enabled: true

Security/MarshalLoad:
  Enabled: true

Security/YAMLLoad:
  Enabled: true
